[package]
name = "rust-life"
version = "0.1.0"
authors = ["Luiz F. A. de Prá <luizfdepra@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8.0"
structopt = "0.2.16"
termion = "1.5.2"
rand = "0.6.5"
liblife = "0.2.0"

[dev-dependencies]
